### ISSUE TITLE
Fill circle on hover

### ISSUE THREAD

**Issue by tomagladiator** [justinmc/jQuery-Open-Carousel#13]
Hello,

I would like to fill the circles with a color when my mouse go hover them.

it is possible ?

Thanks!

**Comment by justinmc** [comment]
Yes you can do this.  You can actually apply CSS directly to the SVG elements, so something like this would do the trick fine:

```
circle:hover {
    fill: #abcdef;
}
```

**Comment by tomagladiator** [comment]
Thanks a lot @justinmc !
