### ISSUE TITLE
Cycle

### ISSUE THREAD

**Issue by sergeygershun** [justinmc/jQuery-Open-Carousel#4]
Is there any way to cycle it?

**Comment by justinmc** [comment]
Unfortunately not right now.  I looked into adding this awhile back, but I ran into problems with supporting all of the existing config parameters in cycle mode.

Now that I see this is a pretty requested feature, I'll take another look at it in a few days when I have time and see if it's not doable...

**Comment by jameswyse** [comment]
:+1:

**Comment by justinmc** [comment]
So sorry this is taking months when I hoped for days, I've been swamped.  I still plan to get around to this for anyone hoping for it...

**Comment by justinmc** [comment]
Got it implemented as a config paramter.  Just update to the latest version and add data-ocarousel-cycle="true" to your .ocarousel div and it will scroll forever in either direction.

You can check out a live example here http://justinmccandless.com/demos/jQuery-Open-Carousel/examples/cycle/index.html or find the code for the example in the repository here https://github.com/justinmc/jQuery-Open-Carousel/tree/master/examples/cycle.

I basically create 2 extra copies of your slides, one before and one after the visible ones, and cycle them treadmill style so it looks infinite to the user.

Thanks for suggesting this!
