### ISSUE TITLE
Linebreak

### ISSUE THREAD

**Issue by HansieMan** [justinmc/jQuery-Open-Carousel#5]
Maybe i'm overlooking something, but when I put a 'br' tag inside i.e. a 'p' or a 'h3' tag, the line does not break. 
Anyone?

**Comment by HansieMan** [comment]
Already figured it out.
just give the 'br' tag a "float:none" and it works...

**Comment by justinmc** [comment]
Actually I think you've found a quirk in the CSS that should be fixed.  "float" seems to be applied to children of the slides and not just the slides themselves.  Good fix in the meantime, but I'll also fix this soon when I'm back on my home computer...

**Comment by justinmc** [comment]
Alright I am seeing br tags working in the latest version I just updated, you shouldn't have to worry about "float: none;" anymore.  Let me know if you still see any problems.
