### ISSUE TITLE
Support for old versions of IE

### ISSUE THREAD

**Issue by justinmc** [justinmc/jQuery-Open-Carousel#7]
Opening this issue myself for a comment left on my blog: http://justinmccandless.com/blog/Open+Source+jQuery+Carousel#comment-1059879444

Check out the main demo and you'll see some sketchiness for old versions of IE: http://www.justinmccandless.com/demos/jQuery-Open-Carousel/examples/main/index.html

This used to work back to IE6 but support has slipped with new updates.  I'm hoping to get back to the same level of support, as nothing being done should be beyond the scope of IE6.

**Comment by justinmc** [comment]
Should be working again for older versions of IE in the latest commit (1a6e02b65f).

The biggest barrier to getting this working was just a CSS child selector being used, which isn't supported by old IE versions. I implemented a work around and it looks good again.

The only thing I see to watch out for is text not wrapping in the slides. You can probably get around this by removing `white-space: nowrap;` from the parent divs if you run into it, depending on your implementation.

**Comment by scottjbeck** [comment]
Any thoughts on supporting indicators on IE7,8?

**Comment by justinmc** [comment]
The current indicators work using SVG, so that won't work out of the box with IE8 and below.  IE8 and below also don't support border-radius in CSS, so using DOM wouldn't work nicely...

Maybe it would be a good idea to include some default images and degrade to those for old browsers.  You would lose all ability to customize the size, color, etc. for these though, but at least you would see something.  I'm hesitant about adding images to the project, but I'll take a look at this.

Also, it's totally possible to include your own images as indicators with the current API if you or anyone else is in urgent need of a solution.

**Comment by justinmc** [comment]
I went ahead and implemented a png fallback for browsers that don't support SVG.  All existing examples that use indicators should now support this, so you can check it out here for example: http://justinmccandless.com/demos/jQuery-Open-Carousel/examples/main/index.html

I used a pretty basic grey circle png as a CSS sprite.  If you want to change to use your own image, it should be pretty easy to swap in a new image and override the style I added.  I added a brief section in the README about this.
