### ISSUE TITLE
latest updates for cycle support break indicator bubbles

### ISSUE THREAD

**Issue by scottjbeck** [justinmc/jQuery-Open-Carousel#8]
updated to the latest js in the git, and setting:
data-ocarousel-cycle="true"

it causes triple the number indicator dots to show up, and loses control of the active indicator.

the following html code shows me six indicator dots:

<div class="ocarousel" data-ocarousel-cycle="true">
    <div class="ocarousel_window">

        <div class="ocarousel-slide">
            <p>test 1</p>
        </div>
        <div class="ocarousel-slide">
            <p>test 2</p>
        </div>

    </div>
    <div class="ocarousel_indicators"></div>
</div>

**Comment by justinmc** [comment]
Totally forgot to test this, that's exactly what I would imagine would happen given the changes.  Will fix this right now, thanks for finding this.

**Comment by justinmc** [comment]
Fixed, should have only 1 set of indicators and light them up intuitively now.

**Comment by scottjbeck** [comment]
Great, thanks for the quick fix!
